load("//build/bazel_mgk_rules:mgk_ddk_ko.bzl", "define_mgk_ddk_ko")

package(
    default_visibility = [
        "//visibility:public",
    ],
)

define_mgk_ddk_ko(
    name = "mainaf",
    srcs = glob([
          "**/*.c",
          "**/*.h",
    ]),
    includes = [
        ".",
    ],
    copts = [
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/lens/vcm/proprietary/main/inc",
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/lens/vcm/proprietary/main/common/lc898122af",
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/lens/vcm/proprietary/main/common/lc898212xdaf/inc",
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/lens/vcm/proprietary/main/common/mot_bogota_gt9764af",
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/lens/vcm/proprietary/main/common/aw86006ois",
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/lens/vcm/proprietary/main/common/mot_cancunf_aw86006af",
        "-I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/lens/vcm/proprietary/main/common/mot_cancunf_aw86006vcmyovaaf",
    ],
    out = "mainaf.ko",
)
